version: '3'
services:
  backend:
    image: titipipers/backend_image
    ports:
      - "8080:8080"
    networks:
      default:
        ipv4_address: 192.168.30.2
    depends_on:
      - "db"
  db:
    image: titipipers/database_image
    ports:
      - "8082:8082"
      - "9092:9092"
    networks:
      default:
        ipv4_address: 192.168.30.3
  frontend:
    image: titipipers/frontend_image
    ports:
      - "80:80"
    networks:
      default:
        ipv4_address: 192.168.30.1
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.30.0/24